import Link from "next/link";

export default function TermsPage() {
  return (
    <main className="min-h-screen">
      <nav className="sticky top-0 z-50 flex items-center justify-between px-6 py-4 border-b border-surface2 bg-parchment">
        <Link href="/" className="font-mech text-xs uppercase tracking-[0.2em] text-cocoa">
          DecaStory
        </Link>
        <Link href="/" className="font-mech text-xs text-steel hover:underline">
          ← Back
        </Link>
      </nav>

      <div className="max-w-2xl mx-auto px-6 py-12">
        <p className="font-mech text-xs uppercase tracking-[0.25em] text-cocoa mb-2">Legal</p>
        <h1 className="font-display text-4xl mb-2">Terms of Service</h1>
        <p className="text-sm text-muted mb-10">Last updated: June 2026</p>

        <div className="space-y-8 text-[15px] leading-relaxed">

          <section>
            <h2 className="font-mech text-xs uppercase tracking-[0.2em] text-muted mb-3">What DecaStory is</h2>
            <p>
              DecaStory is a free, AI-powered interactive fiction app built as a personal project by a UC Davis
              student. By using it, you agree to these terms. If you don't agree, please don't use the app.
            </p>
          </section>

          <section>
            <h2 className="font-mech text-xs uppercase tracking-[0.2em] text-muted mb-3">Using the app</h2>
            <ul className="space-y-2 list-none">
              <li className="pl-4 border-l-2 border-surface2">You must be at least 13 years old to create an account.</li>
              <li className="pl-4 border-l-2 border-surface2">You're responsible for keeping your account credentials secure.</li>
              <li className="pl-4 border-l-2 border-surface2">One account per person. Don't create accounts on behalf of others.</li>
              <li className="pl-4 border-l-2 border-surface2">Don't use DecaStory to generate content that is illegal, harmful, or harassing toward real people.</li>
              <li className="pl-4 border-l-2 border-surface2">Don't attempt to circumvent the daily slide limit or otherwise abuse the shared AI quota.</li>
              <li className="pl-4 border-l-2 border-surface2">Don't reverse-engineer, scrape, or automate requests to the app.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-mech text-xs uppercase tracking-[0.2em] text-muted mb-3">Your content</h2>
            <p className="mb-3">
              The story openings, focus prompts, and feedback comments you write are yours. By submitting them,
              you give DecaStory permission to use them to generate your story and to store them so you can
              return to your work. We don't claim ownership of your creative input.
            </p>
            <p>
              The AI-generated story text produced from your input is generated by Google Gemini and shaped by
              your choices. Its ownership is an unsettled area of law. DecaStory makes no claim on it either.
            </p>
          </section>

          <section>
            <h2 className="font-mech text-xs uppercase tracking-[0.2em] text-muted mb-3">AI-generated content</h2>
            <p className="mb-3">
              Stories are generated by an AI and may contain inaccuracies, inconsistencies, or unexpected content
              despite content rating filters. DecaStory is not responsible for the specific content produced by
              the AI in any individual story.
            </p>
            <p>
              The AI content rating system (G, PG, R) is a best-effort signal to the model, not a guarantee.
              Use your own judgment, especially when sharing stories with others.
            </p>
          </section>

          <section>
            <h2 className="font-mech text-xs uppercase tracking-[0.2em] text-muted mb-3">Service availability</h2>
            <p>
              DecaStory is a free personal project provided as-is with no uptime guarantees. The daily slide
              limit exists to keep the shared AI quota available for all users. The service may change, go
              offline, or shut down at any time without notice. Don't rely on it for anything critical.
            </p>
          </section>

          <section>
            <h2 className="font-mech text-xs uppercase tracking-[0.2em] text-muted mb-3">Shared story links</h2>
            <p>
              When you enable sharing on a story, anyone with the link can read it. You're responsible for
              the content of stories you share publicly. You can disable sharing or delete a story at any time
              from The Vault.
            </p>
          </section>

          <section>
            <h2 className="font-mech text-xs uppercase tracking-[0.2em] text-muted mb-3">Limitation of liability</h2>
            <p>
              DecaStory is provided free of charge and without warranty of any kind. To the maximum extent
              permitted by law, the creator of DecaStory is not liable for any damages arising from your use
              of the app, including but not limited to loss of data, loss of content, or service interruptions.
            </p>
          </section>

          <section>
            <h2 className="font-mech text-xs uppercase tracking-[0.2em] text-muted mb-3">Changes to these terms</h2>
            <p>
              These terms may be updated at any time. The "last updated" date above reflects the most recent
              revision. Continued use of DecaStory after changes constitutes acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="font-mech text-xs uppercase tracking-[0.2em] text-muted mb-3">Contact</h2>
            <p>
              Questions about these terms: <a href="mailto:ajcharles05@ucdavis.edu" className="text-steel underline">ajcharles05@ucdavis.edu</a>
            </p>
          </section>

        </div>

        <div className="mt-12 pt-6 border-t border-surface2 flex gap-6">
          <Link href="/privacy" className="text-sm text-steel hover:underline">Privacy Policy</Link>
          <Link href="/" className="text-sm text-muted hover:text-cocoa">Back to DecaStory</Link>
        </div>
      </div>
    </main>
  );
}
